### PR TITLE
Front-end improvements

### PR DESCRIPTION
**Pull request by aashutoshrathi**
Please run this on your PC and then suggest changes, this PR will last longer. :wink:

### CODE REVIEW

**Comment by anshumanv** [comment]
Design looks awesome, footer is messed up.
Add http://materializecss.com/footer.html
image

**Comment by anshumanv** [comment]
Btw good work scraping data from GSoC site. :wink:

**Comment by anshumanv** [comment]
Removed the current footer, Let's add one from materialize, later.
image

**Review by anshumanv — APPROVED** [review]
LGTM :bowing_man:

**Comment by aashutoshrathi** [comment]
Yes, the Footer and Nav added earlier are messing up.
I might need help and we will renew them.

**Comment by aashutoshrathi** [comment]
Also, might need some help to know why Pagination screwed up? :worried:

**Comment by DipanshKhandelwal** [comment]
@aashutoshrathi is this the color scheme we are going to use?

**Comment by aashutoshrathi** [comment]
Can't say yet, but for Android, Material Theme (Teal and White are cool, I think).
I think we might shift to a better UI colors soon, the focus is on features for now.

**Review by mohitkyadav — COMMENTED** [review]
@aashutoshrathi Your front end changes are not showing up on the category wise post page. Can you do that in this PR?
http://localhost:8000/blog/category/tech/

**Comment by aashutoshrathi** [comment]
@mohitkyadav Yes, I will. Sorry missed that one. :sweat_smile:

**Comment by aashutoshrathi** [comment]
@mohitkyadav check once more now.

**Review by mohitkyadav — APPROVED** [review]
👍

**Comment by aashutoshrathi** [comment]
Just so you know this template is temporary so that we can see features in action.
cc: @Monal5031

**Pull request merged**
